# SITE CONFIGURATION
title: Special Ops Security 
author: Special Ops Security
description: Authorized SBA 8(a) minority-owned small disadvantaged business, specializing in cybersecurity assessment and consulting
baseurl: "/" 
url: "https://specialopssecurity.github.io/" 

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: hero.png #  use the path from /assets/img/ 

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null

include: ['_pages']
permalink: /:title/


plugins:
