# SITE CONFIGURATION
title: Special Ops Security 
author: Special Ops Security
description: Authorized SBA 8(a) minority-owned small disadvantaged business, specializing in cybersecurity assessment and consulting
baseurl: "/" 
url: "https://specialopssecurity.github.io/" 

# THEME SETTINGS
navigation: 
  - {name: 'Audit', link: '/audit'}
  - {name: 'Train', link: '/train'}
  - {name: 'Tools', link: '/tools'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

mobilenav: 
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}


hero_img: hero.png #  use the path from /assets/img/ 

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: Kramdown

include: ['_pages']
permalink: /:title/

plugins:


